### ISSUE TITLE
Incompatible with `@semantic-release/github@5.0.0`

### ISSUE THREAD

**Issue by mysterycommand** [pmowrer/semantic-release-github-pr#28]
Hi there, I just ran into this error in [my project's build on Travis](https://travis-ci.org/fartts/fartts/builds/406685729):

```sh
[Semantic release]: An error occurred while running semantic-release: { TypeError: Cannot destructure property `env` of 'undefined' or 'null'.
    at module.exports (/home/travis/build/fartts/fartts/node_modules/@semantic-release/github/lib/resolve-config.js:4:99)
    at module.exports.pluginConfig (/home/travis/build/fartts/fartts/node_modules/semantic-release-github-pr/src/github-init.js:12:59)
    at /home/travis/build/fartts/fartts/node_modules/semantic-release-github-pr/src/with-github.js:6:18
    at validator (/home/travis/build/fartts/fartts/node_modules/semantic-release/lib/plugins/normalize.js:42:28)
    at pReduce (/home/travis/build/fartts/fartts/node_modules/semantic-release/lib/plugins/pipeline.js:37:40)
    at Promise.all.then.value (/home/travis/build/fartts/fartts/node_modules/p-reduce/index.js:16:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  pluginName: '/home/travis/build/fartts/fartts/node_modules/semantic-release-github-pr/src/index.js' }
{ TypeError: Cannot destructure property `env` of 'undefined' or 'null'.
    at module.exports (/home/travis/build/fartts/fartts/node_modules/@semantic-release/github/lib/resolve-config.js:4:99)
    at module.exports.pluginConfig (/home/travis/build/fartts/fartts/node_modules/semantic-release-github-pr/src/github-init.js:12:59)
    at /home/travis/build/fartts/fartts/node_modules/semantic-release-github-pr/src/with-github.js:6:18
    at validator (/home/travis/build/fartts/fartts/node_modules/semantic-release/lib/plugins/normalize.js:42:28)
    at pReduce (/home/travis/build/fartts/fartts/node_modules/semantic-release/lib/plugins/pipeline.js:37:40)
    at Promise.all.then.value (/home/travis/build/fartts/fartts/node_modules/p-reduce/index.js:16:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  pluginName: '/home/travis/build/fartts/fartts/node_modules/semantic-release-github-pr/src/index.js' }
```

I'm pretty sure the issue is related to [the 5.0.0 release of `@semantic-release/github`](https://github.com/semantic-release/github/releases/tag/v5.0.0) (in particular [this line](https://github.com/semantic-release/github/commit/1f906b4#diff-cf3fc6f1804b0c42979a9e8aeb083e1dR5)) … for now I've rolled back to `semantic-release@15.7.2` (depends on `@semantic-release/github@4.7.2`) and `@semantic-release/changelog@2.1.2` (compatible with `semantic-release@15.7.2`) and everything seems to work again.

**Comment by pmowrer** [comment]
Thanks for the great report and sorry for the delayed response! This looks like an easy fix!

**Comment by pmowrer** [comment]
Actually, a little more involved than it first looks. `semantic-release` 15.7 technically breaks this plugin because it allows for multiple `generateNotes` plugins (not entirely sure how 15.7.2 still works for you). This is fixable but requires a more involved, breaking change. 

To begin with, I'm releasing a fix that restricts the peer dependency range for the current major version of this plugin.

https://github.com/Updater/semantic-release-github-pr/pull/30

**Comment by mysterycommand** [comment]
Thanks for digging in, and no worries about the delay … as I mentioned it's not currently blocking me. I'm happy to help if I can (I'm also pretty busy). In case it's useful, here's my `release.config.js`:

```js
module.exports = {
  verifyConditions: [
    '@semantic-release/changelog',
    '@semantic-release/npm',
    '@semantic-release/git',
    '@semantic-release/github',
  ],
  prepare: [
    '@semantic-release/changelog',
    '@semantic-release/npm',
    {
      path: '@semantic-release/git',
      message: `\
[<%= nextRelease.version %>]\
(https://github.com/fartts/fartts/tree/<%= nextRelease.version%>)\
 - <%= new Date().toLocaleDateString('en-US', {
  year: 'numeric',
  month: 'short',
  day: 'numeric',
  hour: 'numeric',
  minute: 'numeric',
})%> [skip ci]
<%=nextRelease.notes%>`,
    },
  ],
  publish: ['@semantic-release/npm', '@semantic-release/github'],
  npmPublish: false,
  githubPr: {
    analyzeCommits: '@semantic-release/commit-analyzer',
    generateNotes: '@semantic-release/release-notes-generator',
  },
};
```

Maybe it's working because I'm only specifying the one `generateNotes` plugin?

**Comment by pmowrer** [comment]
Thanks for the help @mysterycommand! Just released a version that I believe will fix this. Please reopen if that isn't the case!
