### ISSUE TITLE
Semantic Release Function Name Change

### ISSUE THREAD

**Issue by mysterycommand** [pmowrer/semantic-release-github-pr#35]
I started getting this issue on [my build](https://travis-ci.org/fartts/fartts/builds/459023887):

```sh
[3:47:47 AM] [semantic-release] › ✖  An error occurred while running semantic-release: { TypeError: getGitHead is not a function
    at /home/travis/build/fartts/fartts/node_modules/semantic-release-github-pr/src/with-git-head.js:13:61
    at /home/travis/build/fartts/fartts/node_modules/semantic-release-github-pr/src/with-github.js:10:10
    at validator (/home/travis/build/fartts/fartts/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
    at pReduce (/home/travis/build/fartts/fartts/node_modules/semantic-release/lib/plugins/pipeline.js:37:40)
    at Promise.all.then.value (/home/travis/build/fartts/fartts/node_modules/p-reduce/index.js:16:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  pluginName:
   '/home/travis/build/fartts/fartts/node_modules/semantic-release-github-pr/src/index.js' }
{ TypeError: getGitHead is not a function
    at /home/travis/build/fartts/fartts/node_modules/semantic-release-github-pr/src/with-git-head.js:13:61
    at /home/travis/build/fartts/fartts/node_modules/semantic-release-github-pr/src/with-github.js:10:10
    at validator (/home/travis/build/fartts/fartts/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
    at pReduce (/home/travis/build/fartts/fartts/node_modules/semantic-release/lib/plugins/pipeline.js:37:40)
    at Promise.all.then.value (/home/travis/build/fartts/fartts/node_modules/p-reduce/index.js:16:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  pluginName:
   '/home/travis/build/fartts/fartts/node_modules/semantic-release-github-pr/src/index.js'
```

Looking at [the changes between 15.12.0 and 15.12.1](https://github.com/semantic-release/semantic-release/compare/v15.12.0...v15.12.1) I noticed [this commit](https://github.com/semantic-release/semantic-release/commit/9f5645cfa0a6315149072b5b1c1c7f5bb5eb1fe2) which renames ("harmonizes") the exported function being used [here](https://github.com/Updater/semantic-release-github-pr/blob/master/src/with-git-head.js#L1). I think it's as simple as:

```diff
- const { gitHead: getGitHead } = require('semantic-release/lib/git');
+ const { getGitHead } = require('semantic-release/lib/git');
```

**Comment by pmowrer** [comment]
This plugin has been updated to work with `semantic-release` v16+ and no longer has to rely on this internal part of `semantic-release`
