### ISSUE TITLE
Failure running on Github Actions 

### ISSUE THREAD

**Issue by diogokiss** [pmowrer/semantic-release-github-pr#55]
I'm not sure if I'm doing something wrong, but when I run it I get the following error:

**Execution**: https://github.com/diogokiss/semantic-release-test/runs/6336333222?check_suite_focus=true
**Workflow**: https://github.com/diogokiss/semantic-release-test/actions/runs/2287307333/workflow

``` 
[7:08:24 PM] [semantic-release] › ℹ  Running semantic-release version 19.0.2
[7:08:24 PM] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError: Reflect.defineProperty called on non-object
    at Object.defineProperty (<anonymous>)
    at /home/runner/work/semantic-release-test/semantic-release-test/node_modules/semantic-release/lib/plugins/index.js:22:25
    at Array.forEach (<anonymous>)
    at /home/runner/work/semantic-release-test/semantic-release-test/node_modules/semantic-release/lib/plugins/index.js:20:36
    at Array.reduce (<anonymous>)
    at module.exports (/home/runner/work/semantic-release-test/semantic-release-test/node_modules/semantic-release/lib/plugins/index.js:14:34)
    at module.exports (/home/runner/work/semantic-release-test/semantic-release-test/node_modules/semantic-release/lib/get-config.js:84:35)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async module.exports (/home/runner/work/semantic-release-test/semantic-release-test/node_modules/semantic-release/index.js:265:[32](https://github.com/diogokiss/semantic-release-test/runs/6336313422?check_suite_focus=true#step:4:32))
    at async module.exports (/home/runner/work/semantic-release-test/semantic-release-test/node_modules/semantic-release/cli.js:55:5)
TypeError: Reflect.defineProperty called on non-object
    at Object.defineProperty (<anonymous>)
    at /home/runner/work/semantic-release-test/semantic-release-test/node_modules/semantic-release/lib/plugins/index.js:22:25
    at Array.forEach (<anonymous>)
    at /home/runner/work/semantic-release-test/semantic-release-test/node_modules/semantic-release/lib/plugins/index.js:20:36
    at Array.reduce (<anonymous>)
    at module.exports (/home/runner/work/semantic-release-test/semantic-release-test/node_modules/semantic-release/lib/plugins/index.js:14:34)
    at module.exports (/home/runner/work/semantic-release-test/semantic-release-test/node_modules/semantic-release/lib/get-config.js:84:35)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async module.exports (/home/runner/work/semantic-release-test/semantic-release-test/node_modules/semantic-release/index.js:265:32)
    at async module.exports (/home/runner/work/semantic-release-test/semantic-release-test/node_modules/semantic-release/cli.js:55:5)
```

**Comment by pmowrer** [comment]
Thanks for the report and sorry for the long delay! Instructions for GitHub Actions were added to the README. Hopefully that resolves, else feel free to open up

https://github.com/pmowrer/semantic-release-github-pr/pull/59
